[tool.black]
line-length = 119
target-version = ['py312']
include = '\.pyi?$'
extend-exclude = '''
/(
    # Directories
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.pytest_cache
  | \.ruff_cache
  | \.nox
  | \.tox
  | \.venv
  | venv
  | _build
  | buck-out
  | build
  | dist
  | scratch
  | repos
| experiments/.*/logs
  | experiments/.*/results
  | experiments/.*/checkpoints
  | experiments/.*/data
)/
'''
