import pytest

import cyto_assist


def test_package_has_version() -> None:
    """Test that the package has a version defined."""
    version = getattr(cyto_assist, "__version__", None)
    assert version is not None, "Package __version__ is not defined"


import importlib

def test_package_import() -> None:
    """Test that the main components can be imported."""

    # These are the default modules generated by the template cookiecutter.json
    expected_modules = ["data", "features", "models", "modules", "executors", "app", "utils"]

    for module in expected_modules:
        mod = importlib.import_module(f"cyto_assist.{module}")
        assert mod is not None, f"Module {module} could not be imported"



def test_basic_benchmark() -> None:
    """Test standard array allocations and basic math for naive benchmarking."""
    import numpy as np
    import time

    start = time.time()
    arr = np.random.randn(1000, 1000)
    res = arr @ arr.T
    duration = time.time() - start

    assert res.shape == (1000, 1000)
    assert duration < 5.0, f"Benchmark took too long: {duration}s"


@pytest.mark.skip(reason="This decorator should be removed when test passes.")
def test_example():
    assert 1 == 0  # This test is designed to fail.
